import { ApplyResult, Card, GameDefinition, GameState, Move, Pile, PileKind } from "./types";
export function pile(id: string, kind: PileKind, cards: Card[] = []): Pile { return { id, kind, cards }; }
export function makeState(gameId: string, seed: string, piles: Pile[], meta: Record<string, unknown> = {}): GameState { return { gameId, seed, piles: Object.fromEntries(piles.map((p) => [p.id, p])), moveCount: 0, status: "playing", meta }; }
export function cloneState(state: GameState): GameState { return { ...state, piles: Object.fromEntries(Object.entries(state.piles).map(([id, p]) => [id, { ...p, cards: p.cards.map((c) => ({ ...c })) }])), meta: typeof structuredClone === "function" ? structuredClone(state.meta) : JSON.parse(JSON.stringify(state.meta)) }; }
export function transfer(state: GameState, from: string, to: string, cardIds: string[], faceUp = true): ApplyResult { const next = cloneState(state), source = next.piles[from], target = next.piles[to]; if (!source || !target) return { state, error: "Unknown pile" }; const start = source.cards.findIndex((c) => c.id === cardIds[0]); if (start < 0 || !cardIds.every((id, i) => source.cards[start + i]?.id === id)) return { state, error: "Cards must be a contiguous suffix" }; const moved = source.cards.splice(start, cardIds.length); moved.forEach((card) => { card.faceUp = faceUp; }); target.cards.push(...moved); next.moveCount += 1; return { state: next }; }
export function draw(state: GameState, from: string, to: string, count = 1): ApplyResult { const next = cloneState(state), source = next.piles[from], target = next.piles[to]; if (!source || !target || source.cards.length < count) return { state, error: "Cannot draw" }; const cards = source.cards.splice(source.cards.length - count, count); cards.forEach((c) => { c.faceUp = true; }); target.cards.push(...cards); next.moveCount += 1; return { state: next }; }
export function removeCards(state: GameState, from: string, to: string, ids: string[]): ApplyResult { const next = cloneState(state), source = next.piles[from], target = next.piles[to]; if (!source || !target || ids.some((id) => !source.cards.some((c) => c.id === id))) return { state, error: "Card is not removable" }; for (const id of ids) { const i = source.cards.findIndex((c) => c.id === id); target.cards.push(...source.cards.splice(i, 1)); } next.moveCount += 1; return { state: next }; }
export class GameSession<O = unknown> { readonly definition: GameDefinition<O>; private initial: GameState; private currentState: GameState; private past: GameState[] = []; constructor(definition: GameDefinition<O>, seed: string, options?: O) { this.definition = definition; this.initial = definition.create(seed, options); this.currentState = this.initial; } get state(): GameState { return this.currentState; } move(move: Move): ApplyResult { const result = this.definition.applyMove(this.currentState, move); if (!result.error) { this.past.push(this.currentState); this.currentState = result.state; } return result; } moveBatch(moves: Move[]): ApplyResult { if (!moves.length) return { state: this.currentState }; let next = this.currentState; for (const move of moves) { const result = this.definition.applyMove(next, move); if (result.error) return { state: this.currentState, error: result.error }; next = result.state; } this.past.push(this.currentState); this.currentState = next; return { state: next }; } undo(): GameState { const previous = this.past.pop(); if (previous) this.currentState = previous; return this.currentState; } retry(): GameState { this.past = []; this.currentState = this.definition.create(this.initial.seed, this.initial.meta.options as O | undefined); return this.currentState; } reset(seed: string, options?: O): GameState { this.past = []; this.initial = this.definition.create(seed, options); this.currentState = this.initial; return this.currentState; } hint(): Move | undefined { return this.definition.hint?.(this.currentState); } }
export function applyChecked(state: GameState, move: Move, legalMoves: Move[], fn: () => ApplyResult): ApplyResult { return legalMoves.some((candidate) => JSON.stringify(candidate) === JSON.stringify(move)) ? fn() : { state, error: "Illegal move" }; }
export function top(p: Pile): Card | undefined { return p.cards[p.cards.length - 1]; }
export function faceUpRun(cards: Card[], start: number, sameSuit = false): boolean { for (let i = start; i < cards.length; i += 1) { if (!cards[i].faceUp) return false; if (i > start && (cards[i - 1].rank !== cards[i].rank + 1 || (sameSuit && cards[i - 1].suit !== cards[i].suit))) return false; } return true; }
